commit;
rollback;


CREATE TABLE MC_USERS(
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(15) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
TEL VARCHAR2(15) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
ADDR VARCHAR2(200) NOT NULL,
WAR NUMBER(1) DEFAULT 0,
STATE NUMBER(1) DEFAULT 1 CHECK(STATE IN(0, 1, 2))
);



CREATE TABLE MC_ORDER(
R_NO NUMBER(1) NOT NULL,
R_NAME VARCHAR2(30) NOT NULL,
R_UNAME VARCHAR2(20),
R_CAL DATE,
R_TIME NUMBER(1) CHECK(R_TIME IN(1, 2, 3)),
R_STATIME NUMBER(2),
R_ENDTIME NUMBER(2),
R_USED VARCHAR2(10)
);

CREATE TABLE MC_NOTICE(
NT_NO NUMBER,
NT_TITLE VARCHAR2(50),
NT_CONTENT VARCHAR2(2000),
NT_WRITER VARCHAR2(10) DEFAULT '°ü¸®ÀÚ',
NT_DATE DATE
);

CREATE TABLE MC_ROOMS(
R_NO NUMBER(1) PRIMARY KEY,
R_NAME VARCHAR2(30) NOT NULL,
R_MAX NUMBER(2) NOT NULL,
R_DESC VARCHAR2(500),
R_FILE VARCHAR2(50)
);


SELECT * FROM (SELECT ROWNUM RNUM, A.* FROM (SELECT * FROM BOARD ORDER BY BOARD_NUM DESC ) A ) WHERE RNUM BETWEEN 1 AND 10;

COMMIT;
ROLLBACK;

--½Ç½Ã°£¿¹¾àµ¥ÀÌÅÍ ´õ¹Ì
INSERT INTO MC_ORDER VALUES (1, 'ÃÊÄÚ¶ó¶¼', 'urim', TO_DATE('24/03/28 20:00', 'YY/MM/DD HH24:MI') , '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (2, '³ìÂ÷¶ó¶¼', 'kim', TO_DATE('24/03/28 18:00', 'YY/MM/DD HH24:MI') , '2', '12', '14', '');
INSERT INTO MC_ORDER VALUES (3, '°í±¸¸¶¶ó¶¼', 'lee', TO_DATE('24/03/28 15:00', 'YY/MM/DD HH24:MI') , '3', '15', '18', '');
INSERT INTO MC_ORDER VALUES (4, '¹Ù´Ò¶ó¶ó¶¼', 'bang', TO_DATE('24/03/28 13:00', 'YY/MM/DD HH24:MI') , '1', '15', '16', '');

INSERT INTO MC_ORDER VALUES (2, '³ìÂ÷¶ó¶¼', 'kim', TO_DATE('24/04/17 10:30', 'YY/MM/DD HH24:MI'), '2', '12', '14', '');
INSERT INTO MC_ORDER VALUES (4, '¹Ù´Ò¶ó¶ó¶¼', 'urim', TO_DATE('24/05/18 13:00', 'YY/MM/DD HH24:MI') , '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (1, 'ÃÊÄÚ¶ó¶¼', 'urim', TO_DATE('24/05/25 15:30', 'YY/MM/DD HH24:MI'), '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (3, '°í±¸¸¶¶ó¶¼', 'urim', TO_DATE('24/05/28 15:00', 'YY/MM/DD HH24:MI') , '3', '15', '18', '');


--°ú°Å¿¹¾àµ¥ÀÌÅÍ ´õ¹Ì
INSERT INTO MC_ORDER VALUES (1, 'ÃÊÄÚ¶ó¶¼', 'urim', TO_DATE('24/03/27 15:30', 'YY/MM/DD HH24:MI'), '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (2, '³ìÂ÷¶ó¶¼', 'kim', TO_DATE('24/03/27 10:30', 'YY/MM/DD HH24:MI'), '2', '12', '14', '');
INSERT INTO MC_ORDER VALUES (1, 'ÃÊÄÚ¶ó¶¼', 'urim', TO_DATE('24/03/25 15:30', 'YY/MM/DD HH24:MI'), '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (1, 'ÃÊÄÚ¶ó¶¼', 'urim', TO_DATE('24/03/20 15:30', 'YY/MM/DD HH24:MI'), '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (2, '³ìÂ÷¶ó¶¼', 'kim', TO_DATE('24/03/18 10:30', 'YY/MM/DD HH24:MI'), '2', '12', '14', '');
INSERT INTO MC_ORDER VALUES (3, '°í±¸¸¶¶ó¶¼', 'lee', TO_DATE('24/02/27 15:00', 'YY/MM/DD HH24:MI') , '3', '15', '18', '');
INSERT INTO MC_ORDER VALUES (4, '¹Ù´Ò¶ó¶ó¶¼', 'bang', TO_DATE('24/02/15 13:00', 'YY/MM/DD HH24:MI') , '1', '15', '16', '');
INSERT INTO MC_ORDER VALUES (4, '¹Ù´Ò¶ó¶ó¶¼', 'kim', TO_DATE('24/02/08 13:00', 'YY/MM/DD HH24:MI') , '1', '15', '16', '');


SELECT * FROM MC_ORDER ORDER BY R_CAL DESC;
SELECT * FROM MC_ORDER WHERE R_CAL > SYSDATE ORDER BY R_CAL DESC;
SELECT COUNT(*) FROM MC_ORDER;

SELECT * FROM (SELECT ROWNUM RNUM, A.* FROM (SELECT * FROM MC_ORDER WHERE R_CAL > SYSDATE ORDER BY R_CAL) A) WHERE RNUM BETWEEN 1 AND 10;

SELECT ROWNUM RNUM, A.* FROM (SELECT * FROM MC_ORDER ORDER BY R_CAL DESC ) A;
SELECT ROWNUM RNUM, A.* FROM (SELECT * FROM MC_ORDER WHERE R_CAL > SYSDATE ORDER BY R_CAL DESC) A;

SELECT * FROM MC_ORDER WHERE R_CAL > SYSDATE ORDER BY R_CAL DESC;
SELECT COUNT(*) FROM MC_ORDER WHERE R_CAL > SYSDATE;

INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('admin', '1111', '°ü¸®ÀÚ', '1', 'a', 'a');

INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('aaa', '1111', '±è¾¾', '11', 'a', 'a');
INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('bbb', '1111', 'ÀÌ¾¾', '22', 'a', 'a');
INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('ccc', '1111', '¹æ¾¾', '33', 'a', 'a');
INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('ddd', '1111', 'Á¤¾¾', '44', 'a', 'a');
INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('eee', '1111', 'º¯¾¾', '55', 'a', 'a');
INSERT INTO MC_USERS (ID, PW, NAME, TEL, EMAIL, ADDR) VALUES ('fff', '1111', 'Á¦¾¾', '66', 'a', 'a');

SELECT * FROM (SELECT ROW_NUMBER() OVER (ORDER BY R_NO DESC) AS RNUM, R_NO, R_NAME, R_MAX, R_DESC, R_FILE FROM MC_ROOMS) WHERE RNUM BETWEEN 1 AND 10;
SELECT ROW_NUMBER() OVER (ORDER BY R_NO DESC) AS RNUM, R_NO, R_NAME, R_MAX, R_DESC, R_FILE FROM MC_ROOMS;





SELECT * FROM MC_ROOMS ORDER BY R_NO;

SELECT * FROM MC_ORDER WHERE R_NO = 3;
SELECT R_NO, R_CAL, R_STATIME, R_ENDTIME - 1 FROM MC_ORDER WHERE R_NO = 3 AND R_CAL > SYSDATE;

CREATE TABLE MC_TODAYODTIME(
OD_TIME NUMBER(2) NOT NULL,
OD_STATE VARCHAR2(10) CHECK(OD_STATE IN('°¡´É', 'ºÒ°¡´É'))
);

DROP TABLE MC_TODAYODTIME PURGE;

INSERT INTO MC_TODAYODTIME VALUES (9, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (10, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (11, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (12, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (13, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (14, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (15, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (16, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (17, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (18, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (19, '°¡´É');
INSERT INTO MC_TODAYODTIME VALUES (20, '°¡´É');

