SELECT R_TIME, R_STATIME, R_ENDTIME - 1 FROM MC_ORDER WHERE R_NAME = '冯1' AND R_CAL = '2024-05-29';

SELECT R_TIME, R_STATIME, R_ENDTIME - 1 FROM MC_ORDER WHERE R_NAME = '檬内扼都' AND R_CAL = '2024/03/28';

SELECT R_TIME, R_STATIME, R_ENDTIME - 1 FROM MC_ORDER WHERE R_NAME = '绊备付扼都' AND R_CAL = '2024/03/28';