DROP TABLE MC_ORDER PURGE;
commit;
rollback;


CREATE TABLE MC_USERS(
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(15) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
TEL VARCHAR2(15) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
ADDR VARCHAR2(200) NOT NULL,
WAR NUMBER(1) DEFAULT 0,
STATE NUMBER(1) DEFAULT 0 CHECK(STATE IN(0, 1, 2))
);



CREATE TABLE MC_ORDER(
R_NO NUMBER(1) NOT NULL,
R_NAME VARCHAR2(30) NOT NULL,
R_UNAME VARCHAR2(20),
R_CAL DATE,
R_TIME NUMBER(1) CHECK(R_TIME IN(1, 2, 3)),
R_STATIME NUMBER(2),
R_ENDTIME NUMBER(2),
R_USED VARCHAR2(10)
);

CREATE TABLE MC_NOTICE(
NT_NO NUMBER,
NT_TITLE VARCHAR2(50),
NT_CONTENT VARCHAR2(2000),
NT_WRITER VARCHAR2(10) DEFAULT '관리자',
NT_DATE DATE
);

CREATE TABLE MC_ROOMS(
R_NO NUMBER(1) PRIMARY KEY,
R_NAME VARCHAR2(30) NOT NULL,
R_MAX NUMBER(2) NOT NULL,
R_DESC VARCHAR2(500),
R_FILE VARCHAR2(50)
);

SELECT MAX(R_NO) FROM MC_ROOMS;
INSERT INTO MC_ROOMS VALUES (1, '김건모방', 6, '솰라솰라 방설명', '방사진.jpg');
